TOOLS = tools/funkinisopak tools/funkinarcpak tools/funkinchartpak tools/funkinpicopak tools/funkintimconv tools/psxavenc tools/xainterleave tools/bin2h

all: $(TOOLS)

$(TOOLS):
	cd $@ && $(MAKE)

.PHONY: all $(TOOLS)
