all: \
  src/iso/menu/menu.arc.h \
  src/iso/stage/hud0.tim.h \
  src/iso/stage/hud0weeb.tim.h \
  src/iso/stage/hud1.tim.h \
  src/iso/week1/back.arc.h \
  src/iso/bf/main.arc.h \
  src/iso/dad/main.arc.h \
  src/iso/gf/main.arc.h \
  src/iso/gf/tut.arc.h \
  src/iso/gf/speaker.tim.h

src/iso/%.h: iso/%
	mkdir -p $(dir $@)
	tools/bin2h/bin2h $< $@
