all: \
  $(addsuffix .cht, $(wildcard iso/chart/*.json)) \
  iso/week7/picospeaker.json.cht

iso/chart/%.json.cht: iso/chart/%.json
	tools/funkinchartpak/funkinchartpak $<
iso/week7/picospeaker.json.cht: iso/week7/picospeaker.json
	tools/funkinpicopak/funkinpicopak $<
